-- MySQL Script generated by MySQL Workbench
-- Fri 08 Nov 2019 19:36:05 +06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RailwaysV3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RailwaysV3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RailwaysV3` ;
USE `RailwaysV3` ;

-- -----------------------------------------------------
-- Table `RailwaysV3`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Passenger` (
  `SSN` BIGINT NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `PhoneNum` INT(11) NULL,
  `Email` VARCHAR(45) NULL,
  `Birthday` DATE NULL,
  PRIMARY KEY (`SSN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `SSN` BIGINT NULL,
  PRIMARY KEY (`UserId`),
  INDEX `fk_User_Passenger1_idx` (`SSN` ASC),
  CONSTRAINT `fk_User_Passenger1`
    FOREIGN KEY (`SSN`)
    REFERENCES `RailwaysV3`.`Passenger` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`Station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Station` (
  `StationId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `City` VARCHAR(45) NOT NULL,
  `Lat` DOUBLE NULL,
  `Lon` DOUBLE NULL,
  PRIMARY KEY (`StationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Employee` (
  `UserId` INT NOT NULL,
  `WorkLocation` INT NOT NULL,
  `Role` VARCHAR(45) NULL,
  `Salary` FLOAT NULL,
  `MngrId` INT NULL,
  PRIMARY KEY (`UserId`),
  INDEX `fk_Employee_User1_idx` (`MngrId` ASC),
  INDEX `fk_Employee_Station1_idx` (`WorkLocation` ASC),
  CONSTRAINT `fk_Employee_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `RailwaysV3`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_User1`
    FOREIGN KEY (`MngrId`)
    REFERENCES `RailwaysV3`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Station1`
    FOREIGN KEY (`WorkLocation`)
    REFERENCES `RailwaysV3`.`Station` (`StationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`Train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Train` (
  `TrainId` INT NOT NULL AUTO_INCREMENT,
  `Model` VARCHAR(45) NULL,
  `IssuedDate` DATETIME NULL,
  `Mileage` DOUBLE NULL,
  PRIMARY KEY (`TrainId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Route` (
  `RouteId` INT NOT NULL AUTO_INCREMENT,
  `StationId` INT NOT NULL,
  `TrainId` INT NOT NULL,
  `ArrDate` DATETIME NOT NULL,
  `DepDate` DATETIME NOT NULL,
  `Ordering` INT NOT NULL,
  PRIMARY KEY (`RouteId`, `StationId`, `TrainId`),
  INDEX `fk_Route_Station1_idx` (`StationId` ASC),
  INDEX `fk_Route_Train1_idx` (`TrainId` ASC),
  CONSTRAINT `fk_Route_Station1`
    FOREIGN KEY (`StationId`)
    REFERENCES `RailwaysV3`.`Station` (`StationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Route_Train1`
    FOREIGN KEY (`TrainId`)
    REFERENCES `RailwaysV3`.`Train` (`TrainId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`Carriage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Carriage` (
  `CarriageId` INT NOT NULL AUTO_INCREMENT,
  `TrainId` INT NULL,
  `Type` VARCHAR(45) NULL,
  `TotalSeats` INT NOT NULL,
  PRIMARY KEY (`CarriageId`),
  INDEX `fk_Carriage_Train1_idx` (`TrainId` ASC),
  CONSTRAINT `fk_Carriage_Train1`
    FOREIGN KEY (`TrainId`)
    REFERENCES `RailwaysV3`.`Train` (`TrainId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Book` (
  `RouteId` INT NOT NULL,
  `Arrive_StationId` INT NOT NULL,
  `Depart_StationId1` INT NOT NULL,
  `CarriageId` INT NOT NULL,
  `SeatNum` INT NOT NULL,
  `SSN` BIGINT NOT NULL,
  `Price` DOUBLE NULL,
  `Adult` TINYINT NULL,
  PRIMARY KEY (`RouteId`, `Arrive_StationId`, `Depart_StationId1`, `CarriageId`, `SeatNum`, `SSN`),
  INDEX `fk_Book_Route2_idx` (`Depart_StationId1` ASC, `RouteId` ASC),
  INDEX `fk_Book_Carriage1_idx` (`CarriageId` ASC),
  INDEX `fk_Book_Passenger1_idx` (`SSN` ASC),
  CONSTRAINT `fk_Book_Route1`
    FOREIGN KEY (`RouteId` , `Arrive_StationId`)
    REFERENCES `RailwaysV3`.`Route` (`RouteId` , `StationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Route2`
    FOREIGN KEY (`Depart_StationId1` , `RouteId`)
    REFERENCES `RailwaysV3`.`Route` (`StationId` , `RouteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Carriage1`
    FOREIGN KEY (`CarriageId`)
    REFERENCES `RailwaysV3`.`Carriage` (`CarriageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Passenger1`
    FOREIGN KEY (`SSN`)
    REFERENCES `RailwaysV3`.`Passenger` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RailwaysV3`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RailwaysV3`.`Event` (
  `ManagerId` INT NOT NULL,
  `Route_RouteId` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`ManagerId`, `Route_RouteId`),
  INDEX `fk_Event_Employee1_idx` (`ManagerId` ASC),
  INDEX `fk_Event_Route1_idx` (`Route_RouteId` ASC),
  CONSTRAINT `fk_Event_Employee1`
    FOREIGN KEY (`ManagerId`)
    REFERENCES `RailwaysV3`.`Employee` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Route1`
    FOREIGN KEY (`Route_RouteId`)
    REFERENCES `RailwaysV3`.`Route` (`RouteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
