export const SIGNIN = 'SIGNIN'
export const LOGOUT = 'LOGOUT'
export const REQUEST_SIGNIN = 'REQUEST_SIGNIN'

export const REQUEST_ROUTES = 'REQUEST_ROUTES'
export const GET_ALL_ROUTES = 'GET_ALL_ROUTES'
export const SEARCH_ROUTES = 'SEARCH_ROUTES'
export const ADD_ROUTE = 'ADD_ROUTE'

export const REQUEST_STATIONS = 'REQUEST_STATIONS'
export const GET_STATIONS = 'GET_STATIONS'

export const BOOK_TICKETS = 'BOOK_TICKETS'
export const START_LOADING_TICKETS = 'START_LOADING_TICKETS'

export const SAVE_SEATS = 'SAVE_SEATS'
export const YOU_WILL_BE = 'THE_PURPOSE'
