export const SIGNIN = 'SIGNIN'
export const LOGOUT = 'LOGOUT'
export const REQUEST_SIGNIN = 'REQUEST_SIGNIN'
export const STOP_LOADING_SIGNIN = 'STOP_LOADING_SIGNIN'

export const REQUEST_ROUTES = 'REQUEST_ROUTES'
export const GET_ALL_ROUTES = 'GET_ALL_ROUTES'
export const SEARCH_ROUTES = 'SEARCH_ROUTES'
export const ADD_ROUTE = 'ADD_ROUTE'
export const PICK_ROUTE = 'PICK_ROUTE'

export const REQUEST_STATIONS = 'REQUEST_STATIONS'
export const STOP_REQUEST_STATIONS = 'STOP_REQUEST_STATIONS'
export const GET_STATIONS = 'GET_STATIONS'

export const BOOK_TICKETS = 'BOOK_TICKETS'
export const STOP_LOADING = 'STOP_LOADING'
export const START_LOADING_TICKETS = 'START_LOADING_TICKETS'

export const SAVE_SEATS = 'SAVE_SEATS'
export const CLEAR_SEATS = 'CLEAR_SEATS'

export const START_LOADING_ORDER = 'START_LOADING_ORDER'
export const SAVE_ORDER = 'SAVE_ORDER'
export const CLEAR_ORDER = 'CLEAR_ORDER'

export const YOU_WILL_BE = 'THE_PURPOSE'

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN'
